feat: Refactoring OS

diff --git a/os/Makefile b/os/Makefile
--- a/os/Makefile
+++ b/os/Makefile
@@ -1,53 +1,41 @@
-K=kernel
-U=user
+.RECIPEPREFIX := >
 
-OBJS = \
-  $K/entry.o \
-  $K/start.o \
-  $K/console.o \
-  $K/printf.o \
-  $K/uart.o \
-  $K/kalloc.o \
-  $K/spinlock.o \
-  $K/string.o \
-  $K/main.o \
-  $K/vm.o \
-  $K/proc.o \
-  $K/swtch.o \
-  $K/trampoline.o \
-  $K/trap.o \
-  $K/syscall.o \
-  $K/sysproc.o \
-  $K/bio.o \
-  $K/fs.o \
-  $K/log.o \
-  $K/sleeplock.o \
-  $K/file.o \
-  $K/pipe.o \
-  $K/exec.o \
-  $K/sysfile.o \
-  $K/kernelvec.o \
-  $K/plic.o \
-  $K/virtio_disk.o
+K = kernel
+U = user
+
+BUILD  = out
+OBJDIR = $(BUILD)/obj
+BINDIR = $(BUILD)/bin
+ASMDIR = $(BUILD)/asm
+SYMDIR = $(BUILD)/sym
+MAPDIR = $(BUILD)/map
+IMGDIR = $(BUILD)/img
+GENDIR = $(BUILD)/gen
+
+KERNEL_ELF = $(BINDIR)/kernel/yhsys-kernel.elf
+KERNEL_MAP = $(MAPDIR)/kernel/yhsys-kernel.map
+KERNEL_ASM = $(ASMDIR)/kernel/yhsys-kernel.asm
+KERNEL_SYM = $(SYMDIR)/kernel/yhsys-kernel.sym
+
+FSIMG     = $(IMGDIR)/fs-system.img
+MKFS_HOST = $(BINDIR)/host/mkfs
+USYS_GEN  = $(GENDIR)/usys.S
+USYS_OBJ  = $(OBJDIR)/user/usys.o
 
 # riscv64-unknown-elf- or riscv64-linux-gnu-
-# perhaps in /opt/riscv/bin
-#TOOLPREFIX = 
-
-# Try to infer the correct TOOLPREFIX if not set
 ifndef TOOLPREFIX
 TOOLPREFIX := $(shell if riscv64-unknown-elf-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
-	then echo 'riscv64-unknown-elf-'; \
-	elif riscv64-elf-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
-	then echo 'riscv64-elf-'; \
-	elif riscv64-linux-gnu-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
-	then echo 'riscv64-linux-gnu-'; \
-	elif riscv64-unknown-linux-gnu-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
-	then echo 'riscv64-unknown-linux-gnu-'; \
-	else echo "***" 1>&2; \
-	echo "*** Error: Couldn't find a riscv64 version of GCC/binutils." 1>&2; \
-	echo "*** To turn off this error, run 'gmake TOOLPREFIX= ...'." 1>&2; \
-	echo "***" 1>&2; exit 1; fi)
+ then echo 'riscv64-unknown-elf-'; \
+ elif riscv64-elf-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
+ then echo 'riscv64-elf-'; \
+ elif riscv64-linux-gnu-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
+ then echo 'riscv64-linux-gnu-'; \
+ elif riscv64-unknown-linux-gnu-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
+ then echo 'riscv64-unknown-linux-gnu-'; \
+ else echo "***" 1>&2; \
+ echo "*** Error: Couldn't find a riscv64 version of GCC/binutils." 1>&2; \
+ echo "*** To turn off this error, run 'gmake TOOLPREFIX= ...'." 1>&2; \
+ echo "***" 1>&2; exit 1; fi)
 endif
 $(info $(TOOLPREFIX))
 
@@ -63,20 +51,17 @@ OBJDUMP = $(TOOLPREFIX)objdump
 CFLAGS = -Wall -Werror -Wno-unknown-attributes -O -fno-omit-frame-pointer -ggdb -gdwarf-2
 CFLAGS += -march=rv32gc
 CFLAGS += -mabi=ilp32
-CFLAGS += -MD
 CFLAGS += -mcmodel=medany
 CFLAGS += -ffreestanding
 CFLAGS += -fno-common -nostdlib
 CFLAGS += -fno-builtin-strncpy -fno-builtin-strncmp -fno-builtin-strlen -fno-builtin-memset
 CFLAGS += -fno-builtin-memmove -fno-builtin-memcmp -fno-builtin-log -fno-builtin-bzero
 CFLAGS += -fno-builtin-strchr -fno-builtin-exit -fno-builtin-malloc -fno-builtin-putc
-CFLAGS += -fno-builtin-free
-CFLAGS += -fno-builtin-memcpy -Wno-main
+CFLAGS += -fno-builtin-free -fno-builtin-memcpy -Wno-main
 CFLAGS += -fno-builtin-printf -fno-builtin-fprintf -fno-builtin-vprintf
 CFLAGS += -I.
 CFLAGS += $(shell $(CC) -fno-stack-protector -E -x c /dev/null >/dev/null 2>&1 && echo -fno-stack-protector)
 
-# Disable PIE when possible (for Ubuntu 16.10 toolchain)
 ifneq ($(shell $(CC) -dumpspecs 2>/dev/null | grep -e '[^f]no-pie'),)
 CFLAGS += -fno-pie -no-pie
 endif
@@ -84,115 +69,162 @@ ifneq ($(shell $(CC) -dumpspecs 2>/dev/null | grep -e '[^f]nopie'),)
 CFLAGS += -fno-pie -nopie
 endif
 
+DEPFLAGS = -MMD -MP
 LDFLAGS = -z max-page-size=4096 -m elf32lriscv
 
-$K/kernel: $(OBJS) $K/kernel.ld
-	$(LD) $(LDFLAGS) -T $K/kernel.ld -o $K/kernel $(OBJS) 
-	$(OBJDUMP) -S $K/kernel > $K/kernel.asm
-	$(OBJDUMP) -t $K/kernel | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $K/kernel.sym
+KERNEL_C_SRCS = \
+$(K)/start.c \
+$(K)/console.c \
+$(K)/printf.c \
+$(K)/uart.c \
+$(K)/kalloc.c \
+$(K)/spinlock.c \
+$(K)/string.c \
+$(K)/bootflow.c \
+$(K)/addrspace.c \
+$(K)/taskmgr.c \
+$(K)/irqtrap.c \
+$(K)/syscall_gate.c \
+$(K)/sysproc.c \
+$(K)/sysfile.c \
+$(K)/bio.c \
+$(K)/fs.c \
+$(K)/log.c \
+$(K)/sleeplock.c \
+$(K)/file.c \
+$(K)/pipe.c \
+$(K)/loader_exec.c \
+$(K)/plic.c \
+$(K)/virtio_disk.c
 
-$K/%.o: $K/%.S
-	$(CC) -march=rv32gc -mabi=ilp32 -g -c -o $@ $<
+KERNEL_S_SRCS = \
+$(K)/entry.S \
+$(K)/swtch.S \
+$(K)/trampoline.S \
+$(K)/kernelvec.S
 
-tags: $(OBJS)
-	etags kernel/*.S kernel/*.c
+KERNEL_C_OBJS = $(patsubst $(K)/%.c,$(OBJDIR)/kernel/%.o,$(KERNEL_C_SRCS))
+KERNEL_S_OBJS = $(patsubst $(K)/%.S,$(OBJDIR)/kernel/%.o,$(KERNEL_S_SRCS))
+KERNEL_OBJS = $(KERNEL_C_OBJS) $(KERNEL_S_OBJS)
 
-ULIB = $U/ulib.o $U/usys.o $U/printf.o $U/umalloc.o $U/div64.o
+ULIB_SRCS = $(U)/ulib.c $(U)/printf.c $(U)/umalloc.c $(U)/div64.c
+ULIB_OBJS = $(patsubst $(U)/%.c,$(OBJDIR)/user/%.o,$(ULIB_SRCS))
 
-_%: %.o $(ULIB) $U/user.ld
-	$(LD) $(LDFLAGS) -T $U/user.ld -o $@ $< $(ULIB)
-	$(OBJDUMP) -S $@ > $*.asm
-	$(OBJDUMP) -t $@ | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $*.sym
+USER_APPS = \
+cat banner echo forktest grep guess init kill ln ls mkdir rm rps sh usertests wc logstress forphan dorphan
 
-$U/usys.S : $U/usys.pl
-	perl $U/usys.pl > $U/usys.S
+USER_APP_OBJS = $(addprefix $(OBJDIR)/user/,$(addsuffix .o,$(USER_APPS)))
+USER_BINS = $(addprefix $(BINDIR)/user/_,$(USER_APPS))
 
-$U/usys.o : $U/usys.S
-	$(CC) $(CFLAGS) -c -o $U/usys.o $U/usys.S
+.SECONDARY: $(KERNEL_OBJS) $(ULIB_OBJS) $(USER_APP_OBJS) $(USYS_OBJ)
 
-$U/usertests.o : $U/usertests.c
-	$(CC) $(CFLAGS) -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -Wno-overflow -c -o $U/usertests.o $U/usertests.c
+all: $(KERNEL_ELF) $(FSIMG)
 
-$U/_forktest: $U/forktest.o $(ULIB)
-	# forktest has less library code linked in - needs to be small
-	# in order to be able to max out the proc table.
-	$(LD) $(LDFLAGS) -N -e main -Ttext 0 -o $U/_forktest $U/forktest.o $U/ulib.o $U/usys.o
-	$(OBJDUMP) -S $U/_forktest > $U/forktest.asm
+$(KERNEL_ELF): $(KERNEL_OBJS) $(K)/kernel.ld
+>mkdir -p $(dir $@) $(dir $(KERNEL_MAP)) $(dir $(KERNEL_ASM)) $(dir $(KERNEL_SYM))
+>$(LD) $(LDFLAGS) -Map $(KERNEL_MAP) -T $(K)/kernel.ld -o $@ $(KERNEL_OBJS)
+>$(OBJDUMP) -S $@ > $(KERNEL_ASM)
+>$(OBJDUMP) -t $@ | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $(KERNEL_SYM)
 
-mkfs/mkfs: mkfs/mkfs.c $K/fs.h $K/param.h
-	gcc -Wno-unknown-attributes -I. -o mkfs/mkfs mkfs/mkfs.c
+$(OBJDIR)/kernel/%.o: $(K)/%.c
+>mkdir -p $(dir $@)
+>$(CC) $(CFLAGS) $(DEPFLAGS) -c -o $@ $<
 
-# Prevent deletion of intermediate files, e.g. cat.o, after first build, so
-# that disk image changes after first build are persistent until clean.  More
-# details:
-# http://www.gnu.org/software/make/manual/html_node/Chained-Rules.html
-.PRECIOUS: %.o
+$(OBJDIR)/kernel/%.o: $(K)/%.S
+>mkdir -p $(dir $@)
+>$(CC) -march=rv32gc -mabi=ilp32 -g $(DEPFLAGS) -c -o $@ $<
 
-UPROGS=\
-	$U/_cat\
-	$U/_banner\
-	$U/_echo\
-	$U/_forktest\
-	$U/_grep\
-	$U/_guess\
-	$U/_init\
-	$U/_kill\
-	$U/_ln\
-	$U/_ls\
-	$U/_mkdir\
-	$U/_rm\
-	$U/_rps\
-	$U/_sh\
-	$U/_usertests\
-	$U/_wc\
-	$U/_logstress\
-	$U/_forphan\
-	$U/_dorphan\
+$(USYS_GEN): $(U)/usys.pl
+>mkdir -p $(dir $@)
+>perl $< > $@
 
-fs.img: mkfs/mkfs README $(UPROGS)
-	mkfs/mkfs fs.img README $(UPROGS)
+$(USYS_OBJ): $(USYS_GEN)
+>mkdir -p $(dir $@)
+>$(CC) $(CFLAGS) $(DEPFLAGS) -c -o $@ $<
 
--include kernel/*.d user/*.d
+$(OBJDIR)/user/usertests.o: $(U)/usertests.c
+>mkdir -p $(dir $@)
+>$(CC) $(CFLAGS) $(DEPFLAGS) -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -Wno-overflow -c -o $@ $<
 
-clean: 
-	rm -f *.tex *.dvi *.idx *.aux *.log *.ind *.ilg \
-	*/*.o */*.d */*.asm */*.sym \
-	$K/kernel fs.img \
-	mkfs/mkfs .gdbinit \
-        $U/usys.S \
-	$(UPROGS)
+$(OBJDIR)/user/forphan.o: $(U)/orphan_keeper.c
+>mkdir -p $(dir $@)
+>$(CC) $(CFLAGS) $(DEPFLAGS) -c -o $@ $<
 
-# try to generate a unique GDB port
-GDBPORT = $(shell expr `id -u` % 5000 + 25000)
-# QEMU's gdb stub command line changed in 0.11
-QEMUGDB = $(shell if $(QEMU) -help | grep -q '^-gdb'; \
-	then echo "-gdb tcp::$(GDBPORT)"; \
-	else echo "-s -p $(GDBPORT)"; fi)
+$(OBJDIR)/user/dorphan.o: $(U)/orphan_keeper.c
+>mkdir -p $(dir $@)
+>$(CC) $(CFLAGS) $(DEPFLAGS) -c -o $@ $<
+
+$(OBJDIR)/user/%.o: $(U)/%.c
+>mkdir -p $(dir $@)
+>$(CC) $(CFLAGS) $(DEPFLAGS) -c -o $@ $<
+
+$(BINDIR)/user/_%: $(OBJDIR)/user/%.o $(ULIB_OBJS) $(USYS_OBJ) $(U)/user.ld
+>mkdir -p $(dir $@) $(ASMDIR)/user $(SYMDIR)/user
+>$(LD) $(LDFLAGS) -T $(U)/user.ld -o $@ $< $(ULIB_OBJS) $(USYS_OBJ)
+>$(OBJDUMP) -S $@ > $(ASMDIR)/user/$*.asm
+>$(OBJDUMP) -t $@ | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $(SYMDIR)/user/$*.sym
+
+$(BINDIR)/user/_forktest: $(OBJDIR)/user/forktest.o $(OBJDIR)/user/ulib.o $(USYS_OBJ)
+>mkdir -p $(dir $@) $(ASMDIR)/user $(SYMDIR)/user
+>$(LD) $(LDFLAGS) -N -e main -Ttext 0 -o $@ $^
+>$(OBJDUMP) -S $@ > $(ASMDIR)/user/forktest.asm
+>$(OBJDUMP) -t $@ | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $(SYMDIR)/user/forktest.sym
+
+$(MKFS_HOST): mkfs/mkfs.c $(K)/fs.h $(K)/param.h
+>mkdir -p $(dir $@)
+>gcc -Wno-unknown-attributes -I. -o $@ $<
+
+$(FSIMG): $(MKFS_HOST) README $(USER_BINS)
+>mkdir -p $(dir $@)
+>$(MKFS_HOST) $@ README $(USER_BINS)
+
+.PHONY: qemu qemu-gdb clean print-layout kernel/kernel fs.img mkfs/mkfs
+
+kernel/kernel: $(KERNEL_ELF)
+fs.img: $(FSIMG)
+mkfs/mkfs: $(MKFS_HOST)
+
 ifndef CPUS
 CPUS := 1
 endif
 
-QEMUOPTS = -machine virt -bios none -kernel $K/kernel -m 128M -smp $(CPUS) -nographic
+QEMUOPTS = -machine virt -bios none -kernel $(KERNEL_ELF) -m 128M -smp $(CPUS) -nographic
 QEMUOPTS += -global virtio-mmio.force-legacy=false
-QEMUOPTS += -drive file=fs.img,if=none,format=raw,id=x0
+QEMUOPTS += -drive file=$(FSIMG),if=none,format=raw,id=x0
 QEMUOPTS += -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0
 
-qemu: check-qemu-version $K/kernel fs.img
-	$(QEMU) $(QEMUOPTS)
+qemu: check-qemu-version $(KERNEL_ELF) $(FSIMG)
+>$(QEMU) $(QEMUOPTS)
+
+# try to generate a unique GDB port
+GDBPORT = $(shell expr `id -u` % 5000 + 25000)
+QEMUGDB = $(shell if $(QEMU) -help | grep -q '^-gdb'; \
+ then echo "-gdb tcp::$(GDBPORT)"; \
+ else echo "-s -p $(GDBPORT)"; fi)
 
 .gdbinit: .gdbinit.tmpl-riscv
-	sed "s/:1234/:$(GDBPORT)/" < $^ > $@
+>sed "s/:1234/:$(GDBPORT)/" < $^ > $@
 
-qemu-gdb: $K/kernel .gdbinit fs.img
-	@echo "*** Now run 'gdb' in another window." 1>&2
-	$(QEMU) $(QEMUOPTS) -S $(QEMUGDB)
+qemu-gdb: $(KERNEL_ELF) .gdbinit $(FSIMG)
+>@echo "*** Now run 'gdb' in another window." 1>&2
+>$(QEMU) $(QEMUOPTS) -S $(QEMUGDB)
 
 print-gdbport:
-	@echo $(GDBPORT)
+>@echo $(GDBPORT)
+
+print-layout:
+>@echo "kernel elf: $(KERNEL_ELF)"
+>@echo "fs image  : $(FSIMG)"
+>@echo "apps      : $(USER_BINS)"
 
 QEMU_VERSION := $(shell $(QEMU) --version | head -n 1 | sed -E 's/^QEMU emulator version ([0-9]+\.[0-9]+)\..*/\1/')
 check-qemu-version:
-	@if [ "$(shell echo "$(QEMU_VERSION) >= $(MIN_QEMU_VERSION)" | bc)" -eq 0 ]; then \
-		echo "ERROR: Need qemu version >= $(MIN_QEMU_VERSION)"; \
-		exit 1; \
-	fi
+>@if [ "$(shell echo "$(QEMU_VERSION) >= $(MIN_QEMU_VERSION)" | bc)" -eq 0 ]; then \
+>echo "ERROR: Need qemu version >= $(MIN_QEMU_VERSION)"; \
+>exit 1; \
+>fi
+
+clean:
+>rm -rf $(BUILD) .gdbinit
+
+-include $(KERNEL_OBJS:.o=.d) $(ULIB_OBJS:.o=.d) $(USER_APP_OBJS:.o=.d) $(USYS_OBJ:.o=.d)
